baseURL = "https://leo-mao.github.io"
#baseURL = "https://leo-mao.github.io"

title = "Code Craft"
contentdir    = "content" # required!!!
layoutdir     = "layouts"
publishdir    = "public"
#staticDir     = "static"
#archetypeDir  = "archetypes"
#cacheDir = "/tmp"
#i18nDir = "i18n"

enableRobotsTXT = true
enableEmoji = true
theme = "jane"

paginate = 10
paginatePath = "page"
rssLimit = 15
RSSUri = "rss.xml"
googleAnalytics = ""
copyright = ""

#[outputs]
#home = [ "HTML", "RSS" ]
#section = [ "HTML", "RSS"]

# language support # en-us/ zh-cn/ de-de 
defaultContentlanguage= "en"
hasCJKLanguage = true
[language.en]
  languageCode = "en"

[author]
  name = "Mao"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

#[[menu.main]]
#  name = "Home"
#  weight = 10
#  identifier = "home"
#  url = "/

[[menu.main]]
  name = "archives"
  weight = 20
  identifier = "archives"
  url = "/post/"

[[menu.main]]
  name = "tags"             
  weight = 30
  identifier = "tags"       
  url = "/tags/"            

[[menu.main]]               
  name = "about"       
  weight = 99               
  identifier = "about" 
  url = "/about/"      

timeout  = 10000
uglyURLS = false
useModTimeAsFallback = true
buildDrafts = false
buildExpired = false
buildFuture = false
canonifyURLs = false
cleanDestinationDir = false
config = "config.toml"
defaultContentLanguageInSubdir = true
disableAliases = false
disableHugoGeneratorInject = false
disableKinds = []
disableLiveRoad = false
disablePathToLower = false
enableGitInfo = false
enableMissingTranslationPlaceholders = false
footnoteAnchorPrefix = ""
footnoteReturnLinkContents = ""
forceSyncStatic = false
ignoreCache = false
ignoreFiles = []
log = false
logFile = ""
newContentEditor = ""
noChmod = false
noTimes = false
permalinks = ""
pluralizeListTitles = true
preserveTaxomonyNames = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = true
relativeURLs = false
removePathAccents = false
SectionPagesMenu = ""
stepAnalysis = false
summaryLength = 100
verbose = true
veroseLog = false
watch = true
moreMeta = true

[taxonomies]
  category = "categories"
 # tag = "tags"

[params]
  author = "Mao"
  description  = " Python, Java 和 C++爱好者,目前base杭州滨江"
  since = "2019"
  homeFullContent = false
  rssFullContent = true

  logoTitle = "Code Craft"
  keywords = ["Network", "Linux", "Distribution" , "Python", "Java", "C++", "Vimmer", "Machine Learning", "Git"]
  dataFormatToUse = "2018-01-01"
# Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false
  photoswipe = true
  
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # 社交链接
  a-github = "https://github.com/leo-mao"
